# Site wide configuration

title: Viktor Reshniak's personal site
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Viktor Reshniak
  avatar: bio-photo.jpg
  ornl_logo: ornl_logo.jpg
  mtsu_logo: mtsu_logo.jpg
  dnu_logo: dnu_logo.png
  bio: Staff mathematician at Oak Ridge National Laboratory #"A brief description of yourself."
  email: reshniakv@ornl.gov #emailaddress
  # Do not include the @ symbol in your Twitter username
  twitter: #username
  linkedin: viktorreshniak
  github: #username
  orcid: 0000-0003-1545-4462 # ID Number (ex. 0000-0000-0000-0000)
  researchgate: Viktor_Reshniak #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: kaCEch8AAAAJ&hl #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
